# Generated by Django 2.2.10 on 2020-12-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('party_name', models.CharField(max_length=50)),
                ('party_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='userregister',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
