# Generated by Django 2.2.10 on 2020-12-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201210_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='contact_no',
            field=models.IntegerField(default=True),
        ),
    ]
