# Generated by Django 2.2.10 on 2020-12-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201210_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.IntegerField()),
                ('voter_name', models.CharField(max_length=40)),
                ('selected_party', models.CharField(max_length=50)),
                ('selected_symbol', models.ImageField(upload_to='')),
            ],
        ),
    ]
