# Generated by Django 2.2.10 on 2020-12-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contestantvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='idno',
            field=models.AutoField(default=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
