# Generated by Django 2.2.10 on 2020-12-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201215_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestantvote',
            name='voter_id',
            field=models.IntegerField(default=True, unique=True),
        ),
    ]
